name: Build and Push Docker Image

on:
  push:
    # 任意分支发生以下文件修改都会触发
    paths:
      - 'Dockerfile'
      - 'index.js'
      - 'package.json'
  pull_request:
    # 针对任意分支的 PR 都会触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      # 【新增步骤】自动提取元数据并生成动态标签
      - name: Extract Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/discord_bot
          tags: |
            # 如果是分支提交，生成以分支名命名的标签 (如 :main, :dev)
            type=ref,event=branch
            # 如果是 PR 提交，生成以 pr-号 命名的标签 (如 :pr-12)
            type=ref,event=pr
            # 只有在默认主分支（通常是 main）上提交时，才生成 :latest 标签
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          # 使用上面步骤自动生成的动态标签和标签描述
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=HTTP Server
            org.opencontainers.image.licenses=MIT
          cache-from: type=gha
          cache-to: type=gha,mode=max
